// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RidesRepository is an autogenerated mock type for the RidesRepository type
type RidesRepository struct {
	mock.Mock
}

// UpdateRide provides a mock function with given fields: rideID, source, destination, distance, cost
func (_m *RidesRepository) UpdateRide(rideID string, source string, destination string, distance int32, cost int32) error {
	ret := _m.Called(rideID, source, destination, distance, cost)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRide")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, int32, int32) error); ok {
		r0 = rf(rideID, source, destination, distance, cost)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRidesRepository creates a new instance of RidesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRidesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RidesRepository {
	mock := &RidesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
