version: "3.9"  # Use the latest version for better features

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: careem
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - postgres_data:/var/lib/postgresql/data

  userservice:
    build:
      context: .
      dockerfile: Dockerfile.userservice
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: careem
      USER_SERVICE_PORT: "50051"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "50051:50051"
      - "9090:9090"

  bookingservice:
    build:
      context: .
      dockerfile: Dockerfile.bookingservice
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: careem
      BOOKING_SERVICE_PORT: "50052"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "50052:50052"
      - "9091:9091"

  rideservice:
    build:
      context: .
      dockerfile: Dockerfile.rideservice
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: careem
      RIDE_SERVICE_PORT: "50053"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "50053:50053"
      - "9092:9092"

volumes:
  postgres_data: