// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/ride/ride.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ride struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        int32                  `protobuf:"varint,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Distance      int32                  `protobuf:"varint,4,opt,name=distance,proto3" json:"distance,omitempty"`
	Cost          int32                  `protobuf:"varint,5,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ride) Reset() {
	*x = Ride{}
	mi := &file_proto_ride_ride_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ride) ProtoMessage() {}

func (x *Ride) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ride.ProtoReflect.Descriptor instead.
func (*Ride) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{0}
}

func (x *Ride) GetRideId() int32 {
	if x != nil {
		return x.RideId
	}
	return 0
}

func (x *Ride) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Ride) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Ride) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Ride) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type CreateRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Distance      int32                  `protobuf:"varint,3,opt,name=distance,proto3" json:"distance,omitempty"`
	Cost          int32                  `protobuf:"varint,4,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRideRequest) Reset() {
	*x = CreateRideRequest{}
	mi := &file_proto_ride_ride_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRideRequest) ProtoMessage() {}

func (x *CreateRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRideRequest.ProtoReflect.Descriptor instead.
func (*CreateRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRideRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateRideRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CreateRideRequest) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *CreateRideRequest) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type CreateRideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        int32                  `protobuf:"varint,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRideResponse) Reset() {
	*x = CreateRideResponse{}
	mi := &file_proto_ride_ride_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRideResponse) ProtoMessage() {}

func (x *CreateRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRideResponse.ProtoReflect.Descriptor instead.
func (*CreateRideResponse) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRideResponse) GetRideId() int32 {
	if x != nil {
		return x.RideId
	}
	return 0
}

type GetRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        int32                  `protobuf:"varint,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRideRequest) Reset() {
	*x = GetRideRequest{}
	mi := &file_proto_ride_ride_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRideRequest) ProtoMessage() {}

func (x *GetRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRideRequest.ProtoReflect.Descriptor instead.
func (*GetRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{3}
}

func (x *GetRideRequest) GetRideId() int32 {
	if x != nil {
		return x.RideId
	}
	return 0
}

type UpdateRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        int32                  `protobuf:"varint,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	Ride          *Ride                  `protobuf:"bytes,2,opt,name=ride,proto3" json:"ride,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRideRequest) Reset() {
	*x = UpdateRideRequest{}
	mi := &file_proto_ride_ride_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRideRequest) ProtoMessage() {}

func (x *UpdateRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRideRequest.ProtoReflect.Descriptor instead.
func (*UpdateRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRideRequest) GetRideId() int32 {
	if x != nil {
		return x.RideId
	}
	return 0
}

func (x *UpdateRideRequest) GetRide() *Ride {
	if x != nil {
		return x.Ride
	}
	return nil
}

type UpdateRideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRideResponse) Reset() {
	*x = UpdateRideResponse{}
	mi := &file_proto_ride_ride_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRideResponse) ProtoMessage() {}

func (x *UpdateRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRideResponse.ProtoReflect.Descriptor instead.
func (*UpdateRideResponse) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRideResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_ride_ride_proto protoreflect.FileDescriptor

const file_proto_ride_ride_proto_rawDesc = "" +
	"\n" +
	"\x15proto/ride/ride.proto\x12\x04ride\"\x89\x01\n" +
	"\x04Ride\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\x05R\x06rideId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12\x1a\n" +
	"\bdistance\x18\x04 \x01(\x05R\bdistance\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\x05R\x04cost\"}\n" +
	"\x11CreateRideRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x1a\n" +
	"\bdistance\x18\x03 \x01(\x05R\bdistance\x12\x12\n" +
	"\x04cost\x18\x04 \x01(\x05R\x04cost\"-\n" +
	"\x12CreateRideResponse\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\x05R\x06rideId\")\n" +
	"\x0eGetRideRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\x05R\x06rideId\"L\n" +
	"\x11UpdateRideRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\x05R\x06rideId\x12\x1e\n" +
	"\x04ride\x18\x02 \x01(\v2\n" +
	".ride.RideR\x04ride\".\n" +
	"\x12UpdateRideResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xbc\x01\n" +
	"\vRideService\x12?\n" +
	"\n" +
	"CreateRide\x12\x17.ride.CreateRideRequest\x1a\x18.ride.CreateRideResponse\x12+\n" +
	"\aGetRide\x12\x14.ride.GetRideRequest\x1a\n" +
	".ride.Ride\x12?\n" +
	"\n" +
	"UpdateRide\x12\x17.ride.UpdateRideRequest\x1a\x18.ride.UpdateRideResponseB\x11Z\x0fride-service/pbb\x06proto3"

var (
	file_proto_ride_ride_proto_rawDescOnce sync.Once
	file_proto_ride_ride_proto_rawDescData []byte
)

func file_proto_ride_ride_proto_rawDescGZIP() []byte {
	file_proto_ride_ride_proto_rawDescOnce.Do(func() {
		file_proto_ride_ride_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ride_ride_proto_rawDesc), len(file_proto_ride_ride_proto_rawDesc)))
	})
	return file_proto_ride_ride_proto_rawDescData
}

var file_proto_ride_ride_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_ride_ride_proto_goTypes = []any{
	(*Ride)(nil),               // 0: ride.Ride
	(*CreateRideRequest)(nil),  // 1: ride.CreateRideRequest
	(*CreateRideResponse)(nil), // 2: ride.CreateRideResponse
	(*GetRideRequest)(nil),     // 3: ride.GetRideRequest
	(*UpdateRideRequest)(nil),  // 4: ride.UpdateRideRequest
	(*UpdateRideResponse)(nil), // 5: ride.UpdateRideResponse
}
var file_proto_ride_ride_proto_depIdxs = []int32{
	0, // 0: ride.UpdateRideRequest.ride:type_name -> ride.Ride
	1, // 1: ride.RideService.CreateRide:input_type -> ride.CreateRideRequest
	3, // 2: ride.RideService.GetRide:input_type -> ride.GetRideRequest
	4, // 3: ride.RideService.UpdateRide:input_type -> ride.UpdateRideRequest
	2, // 4: ride.RideService.CreateRide:output_type -> ride.CreateRideResponse
	0, // 5: ride.RideService.GetRide:output_type -> ride.Ride
	5, // 6: ride.RideService.UpdateRide:output_type -> ride.UpdateRideResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_ride_ride_proto_init() }
func file_proto_ride_ride_proto_init() {
	if File_proto_ride_ride_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ride_ride_proto_rawDesc), len(file_proto_ride_ride_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ride_ride_proto_goTypes,
		DependencyIndexes: file_proto_ride_ride_proto_depIdxs,
		MessageInfos:      file_proto_ride_ride_proto_msgTypes,
	}.Build()
	File_proto_ride_ride_proto = out.File
	file_proto_ride_ride_proto_goTypes = nil
	file_proto_ride_ride_proto_depIdxs = nil
}
