// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/booking/booking.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ride struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Distance      int32                  `protobuf:"varint,3,opt,name=distance,proto3" json:"distance,omitempty"`
	Cost          int32                  `protobuf:"varint,4,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ride) Reset() {
	*x = Ride{}
	mi := &file_proto_booking_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ride) ProtoMessage() {}

func (x *Ride) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ride.ProtoReflect.Descriptor instead.
func (*Ride) Descriptor() ([]byte, []int) {
	return file_proto_booking_booking_proto_rawDescGZIP(), []int{0}
}

func (x *Ride) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Ride) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Ride) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Ride) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type Booking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     int32                  `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RideId        int32                  `protobuf:"varint,3,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	Time          string                 `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_proto_booking_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_proto_booking_booking_proto_rawDescGZIP(), []int{1}
}

func (x *Booking) GetBookingId() int32 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *Booking) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Booking) GetRideId() int32 {
	if x != nil {
		return x.RideId
	}
	return 0
}

func (x *Booking) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type BookingDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Distance      int32                  `protobuf:"varint,4,opt,name=distance,proto3" json:"distance,omitempty"`
	Cost          int32                  `protobuf:"varint,5,opt,name=cost,proto3" json:"cost,omitempty"`
	Time          string                 `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingDetails) Reset() {
	*x = BookingDetails{}
	mi := &file_proto_booking_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingDetails) ProtoMessage() {}

func (x *BookingDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingDetails.ProtoReflect.Descriptor instead.
func (*BookingDetails) Descriptor() ([]byte, []int) {
	return file_proto_booking_booking_proto_rawDescGZIP(), []int{2}
}

func (x *BookingDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BookingDetails) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *BookingDetails) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *BookingDetails) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *BookingDetails) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *BookingDetails) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type CreateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Ride          *Ride                  `protobuf:"bytes,2,opt,name=ride,proto3" json:"ride,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_proto_booking_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_booking_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBookingRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateBookingRequest) GetRide() *Ride {
	if x != nil {
		return x.Ride
	}
	return nil
}

type GetBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     int32                  `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRequest) Reset() {
	*x = GetBookingRequest{}
	mi := &file_proto_booking_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRequest) ProtoMessage() {}

func (x *GetBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRequest.ProtoReflect.Descriptor instead.
func (*GetBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_booking_proto_rawDescGZIP(), []int{4}
}

func (x *GetBookingRequest) GetBookingId() int32 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

var File_proto_booking_booking_proto protoreflect.FileDescriptor

const file_proto_booking_booking_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/booking/booking.proto\x12\abooking\"p\n" +
	"\x04Ride\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x1a\n" +
	"\bdistance\x18\x03 \x01(\x05R\bdistance\x12\x12\n" +
	"\x04cost\x18\x04 \x01(\x05R\x04cost\"n\n" +
	"\aBooking\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\x05R\tbookingId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x17\n" +
	"\aride_id\x18\x03 \x01(\x05R\x06rideId\x12\x12\n" +
	"\x04time\x18\x04 \x01(\tR\x04time\"\xa2\x01\n" +
	"\x0eBookingDetails\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12\x1a\n" +
	"\bdistance\x18\x04 \x01(\x05R\bdistance\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\x05R\x04cost\x12\x12\n" +
	"\x04time\x18\x06 \x01(\tR\x04time\"R\n" +
	"\x14CreateBookingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12!\n" +
	"\x04ride\x18\x02 \x01(\v2\r.booking.RideR\x04ride\"2\n" +
	"\x11GetBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\x05R\tbookingId2\x95\x01\n" +
	"\x0eBookingService\x12@\n" +
	"\rCreateBooking\x12\x1d.booking.CreateBookingRequest\x1a\x10.booking.Booking\x12A\n" +
	"\n" +
	"GetBooking\x12\x1a.booking.GetBookingRequest\x1a\x17.booking.BookingDetailsB\x14Z\x12booking-service/pbb\x06proto3"

var (
	file_proto_booking_booking_proto_rawDescOnce sync.Once
	file_proto_booking_booking_proto_rawDescData []byte
)

func file_proto_booking_booking_proto_rawDescGZIP() []byte {
	file_proto_booking_booking_proto_rawDescOnce.Do(func() {
		file_proto_booking_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_booking_booking_proto_rawDesc), len(file_proto_booking_booking_proto_rawDesc)))
	})
	return file_proto_booking_booking_proto_rawDescData
}

var file_proto_booking_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_booking_booking_proto_goTypes = []any{
	(*Ride)(nil),                 // 0: booking.Ride
	(*Booking)(nil),              // 1: booking.Booking
	(*BookingDetails)(nil),       // 2: booking.BookingDetails
	(*CreateBookingRequest)(nil), // 3: booking.CreateBookingRequest
	(*GetBookingRequest)(nil),    // 4: booking.GetBookingRequest
}
var file_proto_booking_booking_proto_depIdxs = []int32{
	0, // 0: booking.CreateBookingRequest.ride:type_name -> booking.Ride
	3, // 1: booking.BookingService.CreateBooking:input_type -> booking.CreateBookingRequest
	4, // 2: booking.BookingService.GetBooking:input_type -> booking.GetBookingRequest
	1, // 3: booking.BookingService.CreateBooking:output_type -> booking.Booking
	2, // 4: booking.BookingService.GetBooking:output_type -> booking.BookingDetails
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_booking_booking_proto_init() }
func file_proto_booking_booking_proto_init() {
	if File_proto_booking_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_booking_booking_proto_rawDesc), len(file_proto_booking_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_booking_booking_proto_goTypes,
		DependencyIndexes: file_proto_booking_booking_proto_depIdxs,
		MessageInfos:      file_proto_booking_booking_proto_msgTypes,
	}.Build()
	File_proto_booking_booking_proto = out.File
	file_proto_booking_booking_proto_goTypes = nil
	file_proto_booking_booking_proto_depIdxs = nil
}
