global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:2112']
  
  - job_name: 'ride-service'
    static_configs:
      - targets: ['ride-service:2113']
  
  - job_name: 'booking-service'
    static_configs:
      - targets: ['booking-service:2114']
