// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: ride.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RidesService_UpdateRide_FullMethodName = "/proto.RidesService/UpdateRide"
)

// RidesServiceClient is the client API for RidesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RidesService and related messages
type RidesServiceClient interface {
	UpdateRide(ctx context.Context, in *UpdateRideRequest, opts ...grpc.CallOption) (*UpdateRideResponse, error)
}

type ridesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRidesServiceClient(cc grpc.ClientConnInterface) RidesServiceClient {
	return &ridesServiceClient{cc}
}

func (c *ridesServiceClient) UpdateRide(ctx context.Context, in *UpdateRideRequest, opts ...grpc.CallOption) (*UpdateRideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRideResponse)
	err := c.cc.Invoke(ctx, RidesService_UpdateRide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RidesServiceServer is the server API for RidesService service.
// All implementations must embed UnimplementedRidesServiceServer
// for forward compatibility.
//
// RidesService and related messages
type RidesServiceServer interface {
	UpdateRide(context.Context, *UpdateRideRequest) (*UpdateRideResponse, error)
	mustEmbedUnimplementedRidesServiceServer()
}

// UnimplementedRidesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRidesServiceServer struct{}

func (UnimplementedRidesServiceServer) UpdateRide(context.Context, *UpdateRideRequest) (*UpdateRideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRide not implemented")
}
func (UnimplementedRidesServiceServer) mustEmbedUnimplementedRidesServiceServer() {}
func (UnimplementedRidesServiceServer) testEmbeddedByValue()                      {}

// UnsafeRidesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RidesServiceServer will
// result in compilation errors.
type UnsafeRidesServiceServer interface {
	mustEmbedUnimplementedRidesServiceServer()
}

func RegisterRidesServiceServer(s grpc.ServiceRegistrar, srv RidesServiceServer) {
	// If the following call pancis, it indicates UnimplementedRidesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RidesService_ServiceDesc, srv)
}

func _RidesService_UpdateRide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RidesServiceServer).UpdateRide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RidesService_UpdateRide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RidesServiceServer).UpdateRide(ctx, req.(*UpdateRideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RidesService_ServiceDesc is the grpc.ServiceDesc for RidesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RidesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RidesService",
	HandlerType: (*RidesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateRide",
			Handler:    _RidesService_UpdateRide_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ride.proto",
}
